# Copyright 2021 Canonical
# See LICENSE file for licensing details.

options:
  repository:
    type: string
    description: |
      URL to repository
  runner-token:
    type: string
    description: |
      GitHub Runner Token
  labels:
    type: string
    description: |
      Labels
